const dotenv = require("dotenv");
const path = require("path");
const Mongoose = require("mongoose");
const User = require("../model/User");
const Transaction = require("../model/Transaction");
const BulkSubscriptionPurchase = require("../model/BulkSubscriptionPurchase");
const BulkSubscriptionCode = require("../model/BulkSubscriptionCode");
const UserSubscription = require("../model/UserSubscription");

const envPath = path.join(__dirname, "../.env");
const result = dotenv.config({ path: envPath });

if (result.error) {
  console.error("Error loading .env file:", result.error);
}

const MONGO_URL = process.env.MONGO_URL || "mongodb://localhost:27017/appraiserassistant";

const cleanupData = async () => {
  try {
    await Mongoose.connect(MONGO_URL);
    console.log("Connected to MongoDB for cleanup");

    // Find all admins and managers
    const users = await User.find({ role: { $in: ["admin", "manager"] } });
    const userIds = users.map((u) => u._id);

    console.log(`Found ${users.length} admin/manager users.`);

    if (userIds.length === 0) {
      console.log("No admins/managers found.");
      process.exit(0);
    }

    // 1. Delete Transactions (Bulk Purchases)
    const deletedTransactions = await Transaction.deleteMany({ userId: { $in: userIds } });
    console.log(`Deleted ${deletedTransactions.deletedCount} Transaction records (Purchases).`);

    // 2. Delete BulkSubscriptionPurchase (The actual bulk purchases shown in UI)
    const deletedBulkPurchases = await BulkSubscriptionPurchase.deleteMany({ adminId: { $in: userIds } });
    console.log(`Deleted ${deletedBulkPurchases.deletedCount} BulkSubscriptionPurchase records.`);

    // 3. Delete Bulk Subscription Codes generated by them
    const deletedCodes = await BulkSubscriptionCode.deleteMany({ adminId: { $in: userIds } });
    console.log(`Deleted ${deletedCodes.deletedCount} BulkSubscriptionCode records.`);

    // 4. Double Check UserSubscriptions (should be 0)
    const deletedSubscriptions = await UserSubscription.deleteMany({ userId: { $in: userIds } });
    console.log(`Deleted ${deletedSubscriptions.deletedCount} remaining UserSubscription records.`);

    console.log("Cleanup completed successfully.");
    process.exit(0);
  } catch (error) {
    console.error("Cleanup failed:", error);
    process.exit(1);
  }
};

cleanupData();
