const express=require("express")
const router=express.Router()
const {carController}=require("../Controller/index")

router.get("/checkZipCode/:zip",carController.checkZipCode)
router.get("/carInfo/:vin",carController.carMarketValue)
router.get("/carinfoByVin/:vin",carController.carinfoByVin)
router.get("/carListing",carController.carListing)
router.get("/saleHistory/:vin",carController.saleHistory)
router.get("/filter",carController.carFilteraton)
router.get("/auction/:vin",carController.auction)
router.get("/premiumVinDecode/:vin",carController.premiumVinDecode)
router.get("/marketValuebyVin",carController.marketValuebyVin)
router.get("/marketValuebyYearAndModel",carController.marketValuebyYearAndModel)
router.get("/premiumplusvindecode/:vin",carController.premiumPlusVinDecode)
router.get("/marketValue/:vin/:state/:mileage",carController.marketValue)
router.post("/generateFreetrialPdf",carController.generateFreetrialPdf)
router.post("/generatePdf",carController.generateReport)
router.post("/homePageApi",carController.homePageApi)
router.get("/getSalvageCarList",carController.getSalvageCarList)
router.post("/generateSalvagePdf",carController.generateSalvagePdf)
router.get("/searchSalvageCar",carController.searchSalvageCar)
router.get("/getSalvageCar",carController.getSalvageCar)
router.get("/fetchCarStat",carController.fetchCarStats)
//new updated code------------------------
router.get("/salvagevaluecarlistings",carController.salvageCarListbyPost)
router.get("/marketvalueCarList",carController.marketingValueCarListbypostforradius)
router.get("/getBasepriceforbid/:vin",carController.getBasePriceForEstimateBid)
router.post("/finalSalvageReeport",carController.finalSalvageReport)
router.post("/finalSalvageReeportSinglePdf",carController.finalSalvageReportSinglePdf)
router.post("/finalSalvageReeportNewVersion",carController.finalSalvageReportNewVersion2)
router.get("/makes", carController.getMakes)
router.get("/models/:makeId", carController.getModels)
router.get("/defaultValues", carController.getDefaults)

module.exports=router