module.exports={
    userRoute:require("./userRoute"),
    carRoute:require("./carRoute"),
    authRoute:require("./authRoute"),
    stripeRoute:require("./stripeRoute"),
    stripeWebhookRoute:require("./stripeWebhookRoute"),
    adminSubscriptionRoute:require("./adminSubscriptionRoute"),
    adminBulkSubscriptionRoute:require("./adminBulkSubscriptionRoute"),
    adminKeyRoute:require("./adminKeyRoute")
}